Admin role
WVU-RANIA-LAB/RANIA-HUB pull request #88
Opened 2024-04-11 02:31 UTC by sarthbpatel

- Completed all the use cases for the admin dashboard
- Updated the styling closer to Figma

2024-04-11 17:27 UTC, kerryran commented
Noted bugs:
1. Edit existing user form, no verification on phone number (format should be XXX-XXX-XXXX)
2. Create new user form, no verification on phone number format

Otherwise, everything seems to be working as intended

2024-04-11 17:37 UTC, wzhengg requested changes
Small changes for more robust types

2024-04-11 17:37 UTC, wzhengg commented on app/lib/actions/admin-actions.ts
> +  role: z.enum(['RESIDENT', 'DOCTOR', 'ADMIN']),
```suggestion
  role: z.nativeEnum(Role),
```

You can import the `Role` type from the Prisma client I think. The reason we want to do this is because if we ever change the Role enum in our Prisma schema, we won't have to manually update `['RESIDENT', 'DOCTOR', 'ADMIN']` here.

2024-04-11 17:37 UTC, wzhengg commented on app/lib/data/admin-data.ts
> +  roleType: 'RESIDENT' | 'DOCTOR' | 'ADMIN',
```suggestion
  roleType: Role,
```

2024-04-11 17:37 UTC, wzhengg commented on app/lib/data/admin-data.ts
> +  roleType: 'RESIDENT' | 'DOCTOR' | 'ADMIN',
```suggestion
  roleType: Role,
```

2024-04-11 17:37 UTC, wzhengg commented on app/ui/admin-dashboard/admin-actions-btns.tsx
> +  roleType: 'RESIDENT' | 'DOCTOR' | 'ADMIN';
```suggestion
  roleType: Role;
```

2024-04-11 17:37 UTC, wzhengg commented on app/ui/admin-dashboard/admin-actions-modal.tsx
> +  roleType?: 'RESIDENT' | 'DOCTOR' | 'ADMIN';
```suggestion
  roleType?: Role;
```

2024-04-11 17:37 UTC, wzhengg commented on app/ui/admin-dashboard/admin-actions-modal.tsx
> +                  <option value="RESIDENT">Resident</option>
```suggestion
                  <option value={Role.RESIDENT}>Resident</option>
```

2024-04-11 17:37 UTC, wzhengg commented on app/ui/admin-dashboard/admin-actions-modal.tsx
> +                  <option value="DOCTOR">Doctor</option>
```suggestion
                  <option value={Role.DOCTOR}>Doctor</option>
```

2024-04-11 17:37 UTC, wzhengg commented on app/ui/admin-dashboard/admin-actions-modal.tsx
> +                  <option value="ADMIN">Admin</option>
```suggestion
                  <option value={Role.ADMIN}>Admin</option>
```

2024-04-12 20:04 UTC, wzhengg approved these changes

2024-04-18 15:27 UTC, wzhengg approved these changes

2024-04-18 18:28 UTC, Mbehanna2019 approved these changes
Everything worked on my end. I was able to Add, Edit, and Delete Residents, Doctors, and Admins.

2024-04-18 20:24 UTC, merged